Serverless/3_serverless_datalake/2.geoserver/geoserver/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('ingest.urls')),
]

Serverless/3_serverless_datalake/2.geoserver/ingest/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CsvUploadView, ShpUploadView, reset, upload_all

app_name = 'ingest'
urlpatterns = [
    path('', TemplateView.as_view(template_name='ingest/index.html'), name="home"),
    path('reset', reset, name="reset"),
    path('upload_all', upload_all, name="upload_all"),
    path('csv/', CsvUploadView.as_view(), name="csv_upload"),
    path('shp/', ShpUploadView.as_view(), name="shp_upload")
]

Serverless/3_serverless_datalake/2.geoserver/ingest/forms.py
import tarfile
import tempfile
from datetime import datetime

import boto3
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

s3 = boto3.resource('s3')


def __init__(self, path):
    self.tmp = tempfile.TemporaryFile()
    self.tarfile = tarfile.open(fileobj=self.tmp, mode='w:')
    self.tarfile.add(path, '.')
    self.tarfile.close()
    self.tmp.flush()
    self.tmp.seek(0)
    self.tarfile = tarfile.open(fileobj=self.tmp, mode='r:')


def is_ascii(value):
    try:
        value.encode('ascii')
    except UnicodeEncodeError:
        raise ValidationError('영어로만 입력해주세요')


class OnlyAsciiField(forms.CharField):
    default_validators = [is_ascii]


def default():
    return f"{datetime.today()} upload file from geoserver"


class S3UploadForm(forms.Form):
    description = OnlyAsciiField(max_length=50, required=True, help_text="자료에 대한 간단한 설명을 영어로 적어주요",
                                 )
    uploader = OnlyAsciiField(max_length=10, required=True, help_text="업로더 이름을 영어로 입력하세요")
    research_date = forms.CharField(required=True, help_text="조사 날짜")


class CsvUploadForm(S3UploadForm):
    point_csv = forms.FileField(required=True,
                                validators=[FileExtensionValidator(allowed_extensions=['csv'])],
                                help_text='gps 좌표 정보가 담긴 csv파일')
    info_csv = forms.FileField(required=True,
                               validators=[FileExtensionValidator(allowed_extensions=['csv'])],
                               help_text='수목 정보가 담긴 csv파일')


class ShpUploadForm(S3UploadForm):
    shp = forms.FileField(required=True,
                          validators=[FileExtensionValidator(allowed_extensions=['shp'])],
                          help_text="shp 파일")
    shx = forms.FileField(required=True,
                          validators=[FileExtensionValidator(allowed_extensions=['shx'])],
                          help_text="shx 파일")
    dbf = forms.FileField(required=True,
                          validators=[FileExtensionValidator(allowed_extensions=['dbf'])],
                          help_text="dbf 파일")
    prj = forms.FileField(required=True,
                          validators=[FileExtensionValidator(allowed_extensions=['prj'])],
                          help_text="prj 파일")
    cpg = forms.FileField(required=True,
                          validators=[FileExtensionValidator(allowed_extensions=['cpg'])],
                          help_text="cpg 파일")

Serverless/3_serverless_datalake/2.geoserver/ingest/views.py
# Create your views here.
import os
import shutil
import tarfile
import tempfile
from datetime import datetime

import boto3
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.views.generic.edit import FormView

from .forms import CsvUploadForm, ShpUploadForm
from .util import get_bucket_name, get_prefix_obj_list, make_hashid, reset_s3

s3 = boto3.resource('s3')
s3_cli = boto3.client('s3')


def upload_file(key: str, tmp_name, metadata: dict = None) -> bool:
    bucket = get_bucket_name()
    # 아직 s3배포 전일 경우 배포 실패
    if bucket is None:
        return False
    metadata = metadata or {}
    metadata['upload_by'] = "geoserver"
    with open(tmp_name, 'rb') as file:
        s3.Object(bucket, key).put(
            Body=file.read(),
            ContentEncoding="gzip",
            Metadata=metadata
        )
    return True


def get_file_list(bucket, prefix):
    objs = get_prefix_obj_list(bucket, prefix)
    result = []
    if objs:
        for obj in objs:
            obj_info = s3_cli.get_object(
                Bucket=bucket,
                Key=obj,
            )
            result.append({
                "key_name": obj.split('/')[-1],
                "timestamp": obj_info['LastModified'],
                "metadata": obj_info['Metadata']
            })
    return result or None


class UploadView(FormView):
    def save_to_tmp(self, obj):
        tmp_obj = tempfile.NamedTemporaryFile(delete=False)
        with open(tmp_obj.name, 'wb') as f:
            shutil.copyfileobj(obj, f)
        return tmp_obj

    def make_tar_gz(self, files: dict):
        """
        파일 목록을 받아 각각 임시 파일로 저장후 압축파일 생성
        :param files: { "파일명":file_obj }
        :return:
        """
        save_files = {name: self.save_to_tmp(file).name for name, file in zip(files.keys(), files.values())}
        tar_file = tempfile.NamedTemporaryFile(delete=False)
        with tarfile.open(tar_file.name, mode='w:gz') as tar:
            for name, tmp_name in zip(save_files.keys(), save_files.values()):
                tar.add(tmp_name, arcname=name)
        return tar

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # s3버킷 상태 추가
        bucket = get_bucket_name()

        if bucket:
            bucket_url = f"https://s3.console.aws.amazon.com/s3/buckets/{bucket}/"
            obj_url_prefix = f"https://s3.console.aws.amazon.com/s3/object/{bucket}"
            context['bucket_name'] = bucket
            context['bucket_url'] = bucket_url
            context['obj_url_prefix'] = obj_url_prefix
            context["csv_files"] = get_file_list(bucket, 'csv')
            context["csv_url"] = f"{bucket_url}csv/"
            context["shp_files"] = get_file_list(bucket, 'shp')
            context['shp_url'] = f"{bucket_url}shp/"
            context["json_files"] = get_file_list(bucket, 'json')
            context["json_url"] = f"{bucket_url}json/"

        return context


class CsvUploadView(UploadView):
    template_name = 'ingest/csv.html'
    form_class = CsvUploadForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if not form.is_valid():
            context = self.get_context_data()
            context['sucess'] = False
            return TemplateResponse(self.request, self.template_name, context=context)
        hash_name = make_hashid()
        tar_file = self.make_tar_gz({
            "point.csv": form.files['point_csv'],
            "tree.csv": form.files['info_csv'],
        })
        metadata = {
            "description": form.data['description'],
            "uploader": form.data['uploader'],
            "research_date": form.data['research_date']
        }
        key = f"csv/{hash_name}.tar.gz"
        context = self.get_context_data()
        if upload_file(key, tar_file.name, metadata=metadata):
            context['success'] = True
            return TemplateResponse(self.request, self.template_name, context=context)
        else:
            context['success'] = False
            return TemplateResponse(self.request, self.template_name, context=context)


class ShpUploadView(UploadView):
    template_name = 'ingest/shp.html'
    form_class = ShpUploadForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        hash_name = make_hashid()
        tar_file = self.make_tar_gz({
            f"{hash_name}.shp": form.files['shp'],
            f"{hash_name}.shx": form.files['shx'],
            f"{hash_name}.dbf": form.files['dbf'],
            f"{hash_name}.prj": form.files['prj'],
            f"{hash_name}.cpg": form.files['cpg'],
        })
        metadata = {
            "description": form.data['description'],
            "uploader": form.data['uploader'],
            "research_date": form.data['research_date']
        }
        key = f"shp/{hash_name}.tar.gz"
        context = self.get_context_data()
        if upload_file(key, tar_file.name, metadata=metadata):
            context['success'] = True
            return TemplateResponse(self.request, self.template_name, context=context)
        else:
            context['success'] = False
            return TemplateResponse(self.request, self.template_name, context=context)


def reset_csv_s3(request):
    reset_s3('csv')
    context = {
        'form': CsvUploadForm(),
        'reset_success': "csv 폴더를 초기화 했습니다",
        's3_console_url': "https:/asd.com",
        'ddb_console_url': "https:/asd.com"
    }
    return TemplateResponse(request, 'ingest/csv.html', context=context)


def reset(request):
    reset_s3()
    redirect_to = request.GET.get('next', '')
    if redirect_to:
        return redirect(redirect_to)
    return redirect("ingest:home")


def upload_all(request):
    reset_s3()
    bucket = get_bucket_name()
    if bucket:
        for file in files:
            with open(file, 'rb') as f:
                s3.Object(bucket, f"shp/{file.split('/')[-1]}").put(
                    Body=f.read(),
                    ContentEncoding="gzip",
                    Metadata={
                        'upload_by': 'geoserver',
                        'uploader': 'autoupload',
                        "description": 'auto upload shp file',
                        "research_date": f"{datetime.now()}"
                    }
                )
    return redirect("ingest:home")

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/bucket.html
<div class="ui segments">
    <div class="ui attached header">
        <h4><i class="warehouse icon"></i> <a target="_blank" rel="noopener noreferrer"
                      href={{ bucket_url }}>{{ bucket_name }}</a>버킷 상태</h4>
    </div>
    <div class="ui segment">
        <div class="ui list divided items">
            <div class="item">
                <i class="folder icon"></i>
                <div class="content">
                    <div class="header"><a target="_blank" rel="noopener noreferrer"
                                           href={{ csv_url }}>csv</a>
                    </div>
                    <div class="description">업로드된 csv 압축파일</div>
                    <div class="list  divided items">
                        {% with icon="file archive" %}
                            {% include "ingest/bucket_files.html" with icon=icon files=csv_files dir="csv" %}
                        {% endwith %}
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="folder icon"></i>
                <div class="content">
                    <div class="header"><a target="_blank" rel="noopener noreferrer"
                                           href={{ shp_url }}>shp</a>
                    </div>
                    <div class="description">업로했거나 csv에서 변환된 shp 압축파일들</div>
                    <div class="list  divided items">
                        {% with icon="archive" %}
                            {% include "ingest/bucket_files.html" with icon=icon files=shp_files dir="shp" %}
                        {% endwith %}
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="folder icon"></i>
                <div class="content">
                    <div class="header"><a target="_blank" rel="noopener noreferrer"
                                           href={{ json_url }}>json</a>
                    </div>
                    <div class="description">변환된 json파일 목록</div>
                    <div class="list divided items">
                        {% with icon="file" %}
                            {% include "ingest/bucket_files.html" with icon=icon files=json_files dir="json" %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/bucket_files.html
{% if files %}
    {% for obj in files %}
        <div class="item">
            <i class="{{ icon }} icon"></i>
            <div class="content">
                <div class="header"><a target="_blank" rel="noopener noreferrer" href="{{ obj_url_prefix }}/{{ dir }}/{{ obj.key_name }}">
                    {{ obj.key_name }}</a></div>
                <div class="description">

                    <div class="ui labels">
                        <span>obj metadata</span>
                        <div class="ui label">
                            <i class="calendar icon"></i>
                            <div class="detail">{{ obj.timestamp }}</div>
                        </div>
                        {% for key,value in obj.metadata.items %}
                            <div class="ui label">
                                {{ key }}
                                <div class="detail">{{ value }}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
{% else %}
    <div class="item">
        <i class="bug icon"></i>
        <div class="content">
            <div class="header">no files!</div>
            <div class="description">let's upload!</div>
        </div>
    </div>
{% endif %}

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/csv.html
{% extends 'base.html' %}
{% block body %}
    <form class="ui form segments" enctype="multipart/form-data" action="{% url "ingest:csv_upload" %}" method="post">
        {% csrf_token %}
        <div class="ui attached header">
            <h1>탐방로 수목 조사자료 업로드(csv)</h1>
        </div>
        <div class="ui three steps segment">
            <div class="active step">
                <i class="cloud upload icon"></i>
                <div class="content">
                    <div class="title">geoserver</div>
                    <div class="description">형식 확인후 csv폴더에 자료 업로드</div>
                </div>
            </div>
            <div class="step">
                <i class="warehouse icon"></i>
                <div class="content">
                    <div class="title">s3</div>
                    <div class="description">파일 추가시 람다 트리거 발생</div>
                </div>
            </div>
            <div class="step">
                <i class="bolt icon"></i>
                <div class="content">
                    <div class="title">람다</div>
                    <div class="description">
                        자료를 shp로 변환후 shp폴더 저장<br>
                        및 DDB에 csv 파일 색인 추가
                    </div>
                </div>
            </div>
        </div>
        {% include 'ingest/message.html' %}
        {% include 'ingest/default_uplaod_fields.html' %}
        {% include 'ingest/upload_fileds.html' %}

        <div class="ui bottom attached clearing segment">


            <div class="ui right floated buttons">
                <button class="ui button" type="reset">
                    <i class="undo icon"></i>다시하기
                </button>
                <div class="or"></div>
                <button class="ui primary button" type="submit">
                    <i class="cloud upload icon"></i>업로드
                </button>

            </div>
            <a href="{% url 'ingest:reset' %}?next=ingest:csv_upload" class="ui red button">s3 초기화</a>
            <a class="ui red button" target="_blank" rel="noopener noreferrer"
               href="https://ap-northeast-2.console.aws.amazon.com/dynamodb/home?region=ap-northeast-2#tables:selected=gis-datalake-shp-metadata;tab=items">shp
                메타데이터 초기화 하기</a>
        </div>
    </form>
    {% if bucket_name %}
        {% include 'ingest/bucket.html' with bucket_name=bucket_name %}
    {% endif %}
{% endblock %}

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/default_uplaod_fields.html
<div class="ui attached segment">
    <div class="required field">
        <label>업로더 이름</label>
        <input type="text" name="uploader" maxlength="10" required="" id="id_uploader"
               placeholder="{{ form.uploader.help_text }}">
        {% if form.uploader.errors %}
            <div class="ui negative message">
                {{ form.uploader.errors }}
            </div>
        {% endif %}
    </div>
</div>
<div class="ui attached segment">
    <div class="required field">
        <label>자료 설명</label>
        <input type="text" name="description" maxlength="50" required="" id="id_description"
               placeholder="{{ form.description.help_text }}">
        {% if form.description.errors %}
            <div class="ui negative message">
                {{ form.description.errors }}
            </div>
        {% endif %}
    </div>
</div>
<div class="ui attached segment">

    <div class="required calendar field">
        <label>조사 날짜</label>
        <div class="ui calendar" id="dateselect">
            <div class="ui input left icon">
                <i class="calendar icon"></i>
                <input type="text" name="research_date" required="" id="id_research_date">
            </div>
        </div>

        {% if form.research_date.errors %}
            <div class="ui negative message">
                {{ form.research_date.errors }}
            </div>
        {% endif %}
    </div>
</div>
<script type="text/javascript">
    $('#dateselect').calendar({
        monthFirst: false,
        type: 'date',
        formatter: {
            date: function (date, settings) {
                if (!date) return '';
                var day = date.getDate();
                var month = date.getMonth() + 1;
                var year = date.getFullYear();
                return year + '/' + month + '/' + day;
            }
        }
    });
</script>

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="ui segments">
        <div class="ui attached header ">
            <h1>GIS DataLake GeoServer</h1>

        </div>
        <div class="ui segment">
            <p>
                축하합니다! 성공적으로 geoserver을 배포했습니다!<br>
                이곳은 datalake를 구축할때 마다 제대로 구현 됬는지 확인 하기 위해<br>
                s3에 자료 업로드 및 s3 파일목록, 다시 테스트 기능이 담긴 곳입니다.<br>
                오로지 원활한 실습을 위해 만들었으며 일반적으로 datalake에서는 이러한 서버가 필요하지는 않습니다.
            </p>
        </div>
        <div class="ui segment">
            <h3>1. 샘플파일을 다운로드 받으세요</h3>
        </div>
        <div class="ui secondary segment">
            <a class="ui button" href="https://github.com/awskrug/handson-labs-2018/raw/master/Serverless/3_serverless_datalake/2.geoserver/upload_sample.zip" download>샘플 파일 다운로드</a>
        </div>
        <div class="ui segment">
            <h3>2. GIS DataLake를 단계별로 구축하고 직접 파일을 업로드 하여 결과를 확인해보세요</h3>
        </div>
        <div class="ui secondary segment">
            <a class="ui button primary" href={% url  "ingest:csv_upload" %}>csv 파일 업로드</a>
            <a class="ui button primary" href={% url  "ingest:shp_upload" %}>shp 파일 업로드</a>
        </div>
        <div class="ui segment">
            <h3>3. 전체 진행 상황을 확인해보세요</h3>
        </div>
        <div class="ui secondary segment">
            <a class="ui button primary" target="_blank" rel="noopener noreferrer"
               href="https://ap-northeast-2.console.aws.amazon.com/xray/home?region=ap-northeast-2#/service-map?timeRange=PT6H">x-ray
                보러가기</a>
            <a class="ui button primary" target="_blank" rel="noopener noreferrer"
               href="https://ap-northeast-2.console.aws.amazon.com/dynamodb/home?region=ap-northeast-2#tables:selected=gis-datalake-shp-metadata;tab=items">shp
                메타데이터 보러가기</a>
        </div>
        <div class="ui segment">
            <h3>4. datalake에 올라간 자료를 아테나와 퀵사이트를 이용해 분석해보세요</h3>
        </div>
        <div class="ui secondary segment">
            <a class="ui button" href="https://github.com/awskrug/handson-labs-2018/raw/master/Serverless/3_serverless_datalake/2.geoserver/all.zip" download>샘플 파일 다운로드</a>
            <a class="ui button primary" target="_blank" rel="noopener noreferrer"
               href="https://ap-northeast-2.console.aws.amazon.com/athena/home">Athena</a>
            <a class="ui button primary" target="_blank" rel="noopener noreferrer"
               href="https://ap-northeast-1.quicksight.aws.amazon.com/sn/start?#">QuickSight</a>
        </div>
        <div class="ui segment">
            <h3>5. 실습을 완료했다면 datalake를 깔끔하게 지워봅시다!</h3>
        </div>
        <div class="ui secondary segment">
            <p>먼저 <a class="ui button primary" href="{% url 'ingest:reset' %}?next=ingest:home">s3
                초기화</a> 한뒤에</p>
            <p>zappa로 배포한 geoserver 리소스와 serverless로 배포한 datalake 리소스를 삭제하시고</p>
            <p>마지막으로 cloud9 인스턴스를 삭제하세요</p>
        </div>
    </div>

{% endblock body %}

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/message.html
{% if success %}
    <div class="ui attached positive message">
        <div class="header">gis datalake에 성공적으로 저장 되었습니다</div>
    </div>
{% endif %}
{% if reset_success %}
    <div class="ui attached positive message">
        <div class="header">{{ reset_success }} </div>
    </div>
{% endif %}

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/shp.html
{% extends 'base.html' %}
{% block body %}
    <form class="ui form segments" enctype="multipart/form-data" action={% url 'ingest:shp_upload' %} method="post">
        {% csrf_token %}
        <div class="ui top attached header">
            <h1>탐방로 수목 조사자료 업로드(shp)</h1>
        </div>
        <div class="ui three top attached steps">
            <div class="active step">
                <i class="cloud upload icon"></i>
                <div class="content">
                    <div class="title">geoserver</div>
                    <div class="description">형식 확인후 shp폴더에 자료 업로드</div>
                </div>
            </div>
            <div class="step">
                <i class="warehouse icon"></i>
                <div class="content">
                    <div class="title">s3</div>
                    <div class="description">파일 추가시 람다 트리거 발생</div>
                </div>
            </div>
            <div class="step">
                <i class="bolt icon"></i>
                <div class="content">
                    <div class="title">람다</div>
                    <div class="description">
                        자료를 geojson로 변환후 json폴더에 저장<br>
                        및 DDB에 json 파일 색인 추가
                    </div>
                </div>
            </div>
        </div>
        {% include 'ingest/message.html' %}
        {% include 'ingest/default_uplaod_fields.html' %}
        {% include 'ingest/upload_fileds.html' %}

        <div class="ui bottom attached clearing segment">
            <div class="ui right floated buttons">
                <button class="ui button" type="reset">
                    <i class="undo icon"></i>다시하기
                </button>
                <div class="or"></div>
                <button class="ui primary button" type="submit">
                    <i class="cloud upload icon"></i>업로드
                </button>
            </div>
            <a href="{% url 'ingest:reset' %}?next=ingest:shp_upload" class="ui red button">s3 초기화</a>
            <a class="ui red button" target="_blank" rel="noopener noreferrer"
               href="https://ap-northeast-2.console.aws.amazon.com/dynamodb/home?region=ap-northeast-2#tables:selected=gis-datalake-shp-metadata;tab=items">shp
                메타데이터 초기화 하기</a>
        </div>
    </form>
    {% if bucket_name %}
        {% include 'ingest/bucket.html' with bucket_name=bucket_name %}
    {% endif %}
{% endblock %}

Serverless/3_serverless_datalake/2.geoserver/ingest/templates/ingest/upload_fileds.html
{% for field in form %}

    {% if field.label  == "Description" %}
    {% elif field.label  == "Uploader" %}
    {% elif field.label == "Research date" %}
    {% else %}
        <div class="ui  segment">
            <a class="ui teal ribbon label">{{ field.help_text }}</a>
            <span>아래에 파일을 드래그 엔 드롭 하세요</span>
        </div>
        {% if field.errors %}
            <div class="ui attached negative message">{{ field.errors }}</div>
        {% endif %}
        <div class="ui  file_input segment">{{ field }}</div>
    {% endif %}

{% endfor %}