Serverless/3_serverless_datalake/2.geoserver/geoserver/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('ingest.urls')),
]

Serverless/3_serverless_datalake/2.geoserver/ingest/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CsvUploadView, ShpUploadView, reset, upload_all

app_name = 'ingest'
urlpatterns = [
    path('', TemplateView.as_view(template_name='ingest/index.html'), name="home"),
    path('reset', reset, name="reset"),
    path('upload_all', upload_all, name="upload_all"),
    path('csv/', CsvUploadView.as_view(), name="csv_upload"),
    path('shp/', ShpUploadView.as_view(), name="shp_upload")
]

Serverless/3_serverless_datalake/2.geoserver/templates/base.html
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans:400" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.1/dist/semantic.min.css">
    <link href="https://cdn.rawgit.com/mdehoog/Semantic-UI-Calendar/76959c6f7d33a527b49be76789e984a0a407350b/dist/calendar.min.css"
          rel="stylesheet" type="text/css"/>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/dropzone@5.4.0/dist/dropzone.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.1/dist/semantic.min.js"></script>
    <script src="https://cdn.rawgit.com/mdehoog/Semantic-UI-Calendar/76959c6f7d33a527b49be76789e984a0a407350b/dist/calendar.min.js"></script>
    <style type="text/css">
        h1 {
            text-align: center;
        }

        .segment.file_input {
            padding: 0px !important;
        }

        input[type="file"] {
            padding-bottom: 30px !important;
            padding-top: 30px !important;
            padding-left: 30px !important;
            width: 100% !important;
        }

    </style>
</head>
<body>
{% block navi %}
    <div class="ui labeled icon menu">
        <a href={% url "ingest:home" %}>
            <img src="https://d1.awsstatic.com/International/ko_KR/banners/Hands-on%20Labs%20LP%20Banner.04c83ecb7c16f458e5723909ee1301e43453ee6b.png"
                 width=450 height=75>
        </a>

        <div class="right  menu">
            <a class="item" href="{% url "ingest:csv_upload" %}">
                <i class="file archive icon"></i>
                csv 업로드
            </a>
            <a class="item" href="{% url "ingest:shp_upload" %}">
                <i class="archive icon"></i>
                shp 업로드
            </a>
        </div>
    </div>
{% endblock %}


<div class="ui centered grid">
    <div class="one wide column"></div>
    <div class="twelve wide column">
        {% block body %}{% endblock %}
    </div>
    <div class="one wide column"></div>
</div>


</body>
</html>